robot_urdf_path: "/home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/robots/teleop2/urdf/teleop2.urdf"
robot_srdf_path: "/home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/robots/teleop2/srdf/teleop2.srdf"
robot_task_path: "/home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/robots/teleop2/task/teleop2_stack.yaml"
robot_is_floating: false
robot_model_type: "RBDL"
solver_type: "OpenSot"
task_name: "arm_control"
task_position: [0.05,0.0,0.0]
task_orientation: [0.0,0.0,0.0]
target_time: [10.0]
homing_time: 10.0