XBotInterface:
  urdf_path: /home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/robots/teleop2/urdf/teleop2.urdf
  srdf_path: /home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/robots/teleop2/srdf/teleop2.srdf

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"

RobotInterface:
   framework_name: "ROS"

## XBot2-related configuration


# hal
xbotcore_device_configs:
    sim: /home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/configs/xbot/teleop2_config/hal/teleop2_gz.yaml
    dummy: /home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/configs/xbot/teleop2_config/hal/teleop2_dummy.yaml


# threads
xbotcore_threads:
    rt_main:  {sched: fifo, prio: 60, period: 0.001, core_id: 2}
    nrt_main: {sched: other, prio: 0, period: 0.005}


# plugins
xbotcore_plugins:

    homing:
        thread: rt_main
        type: homing_example

    ros_io: {thread: nrt_main, type: ros_io}
    ros_control: {thread: nrt_main, type: ros_control, params: {autostart: {type: bool, value: true}}}


# global parameters
xbotcore_param:
    /jm/tx_filter_autostart: {value: true, type: bool}
    /jm/tx_filter_cutoff: {value: 2.0, type: double}
    /jm/enable_safety: {value: false, type: bool}
    /xbot_internal/ros_io/call_timeout: {value: 1.0, type: chrono}
    /rt_main/memory_hooks: {value: true, type: bool}
