robot_urdf_path: "/home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/robots/coman/urdf/coman.urdf"
robot_srdf_path: "/home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/robots/coman/srdf/coman.srdf"
robot_task_path: "/home/liana/catkin_ws/src/CartesioTests/CartesioTestsCpp/robots/coman/task/coman_stack.yaml"
robot_is_floating: true
robot_model_type: "RBDL"
solver_type: "OpenSot"
task_name: "left_hand"
task_position: [0.0,0.05,0.0,0.0,-0.02,0.10]
task_orientation: [0.0,0.0,90.0,0.0,0.0,0.0]
target_time: [3.0,3.0]
homing_time: 3.0