RobotName: "centauro"

GazeboXBotPlugin:
  control_rate: 0.0005
  gains:
    j_arm1_1: {p: 2500, d: 10}
    j_arm1_2: {p: 2500, d: 10}
    j_arm1_3: {p: 2500, d: 10}
    j_arm1_4: {p: 2500, d: 10}
    j_arm1_6: {p: 2500, d: 10}
    j_arm2_1: {p: 2500, d: 10}
    j_arm2_2: {p: 2500, d: 10}
    j_arm2_3: {p: 2500, d: 10}
    j_arm2_4: {p: 2500, d: 10}
    j_arm2_6: {p: 2500, d: 10}
    torso_yaw: {p: 2500, d: 10}
    hip_yaw_1:  &hip_yaw {p: 2500, d: 10}
    hip_yaw_2: *hip_yaw
    hip_yaw_3: *hip_yaw
    hip_yaw_4: *hip_yaw
    hip_pitch_1: &hip_pitch {p: 2500, d: 10}
    hip_pitch_2: *hip_pitch
    hip_pitch_3: *hip_pitch
    hip_pitch_4: *hip_pitch
    knee_pitch_1: &knee_pitch {p: 2500, d: 10}
    knee_pitch_2: *knee_pitch
    knee_pitch_3: *knee_pitch
    knee_pitch_4: *knee_pitch
    ankle_pitch_1: &ankle_pitch {p: 2500, d: 10}
    ankle_pitch_2: *ankle_pitch
    ankle_pitch_3: *ankle_pitch
    ankle_pitch_4: *ankle_pitch
    ankle_yaw_1: &ankle_yaw {p: 2500, d: 10}
    ankle_yaw_2: *ankle_yaw
    ankle_yaw_3: *ankle_yaw
    ankle_yaw_4: *ankle_yaw
    j_wheel_1: &wheel {p: 0, d: 1}
    j_wheel_2: *wheel
    j_wheel_3: *wheel
    j_wheel_4: *wheel

torque_offset:
    71: -0.753321382376
    72: -0.878021620324
    73: 0.352725602718
    76: -0.000691990669113
    75: 0.203120524724
    74: 0.41143531135
    42: -1.80021518429
    41: 0.0452259995711
    46: 0.000563617254118
    43: -1.00207090854
    44: -3.17548146441
    45: -0.380605734378
    61: 0.699208549855
    62: -0.62814474981
    65: -95.5690328889
    64: 0.0415370043935
    63: -0.457692413973
    66: 0.000716904270697
    52: -1.64996117441
    51: -0.306404111445
    55: 0.158380897738
    54: -2.51085540833
    53: 1.0890510881
    56: -0.000697787819546

HALInterface:
  lib_file: "libXBotEcat"
  lib_name: "ETHERCAT"
  IJoint: "libXBotEcat_Joint"
  ISensors:
  #- [[81] , "libXBotEcat_FT"]
   - [[104] , "libXBotEcat_IMU"]
  #IEndEffectors: 
  # - [[110, 111], "libXBotEcat_HeriHand"]

SCPLog:
  remote_username: "centauro"
  remote_ip_address: "10.24.4.77"
  remote_log_folder_path: "/home/centauro/CENTAURO_LOG/CENTAURO_shared"

x_bot_ecat:
  name: XBotCore
  sdo_xddp_prefix :
  # periodic - priority if needed here

ec_board_ctrl:
  eth_iface: rteth0
  sync_cycle_time_ns: 1000000
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false
  use_pipes: false

ec_boards_base:
  use_pipes: false
  fault_power_off: true
  log_level: 1

ec_board_base:
  use_pipes: false

firmware_update:
  #
  fw_path: ../examples/fw_update/fw_test/
  #slave_pos_list: [7]
  #slave_rId_list: [7]
  # all esc
  #slave_pos_list: [0]
  # all BigMotor
  #slave_pos_list: [-1]
  # all MedMotor
  #slave_pos_list: [-2]
  # all LowPower motor
  #slave_pos_list: [-3]
  # all CentAC motor
  slave_pos_list: [-4]
  #slave_pos_list: [1]

  cent_AC:
    m3:
      bin_file: cent_AC_m3.bin
      passwd: 0xA550
    c28:
      bin_file: cent_AC_c28.bin
      passwd: 0xDAD0


XBotCommunicationPlugin:
   ref_policy_ignore:
     - j_wheel_1
     - j_wheel_2
     - j_wheel_3
     - j_wheel_4
     - neck_velodyne


definitions: 
 - &default_arm_imp  	[500.00, 10.0, 1.0, 0.003, 0.40]  
 - &default_arm_imp_lp 	[300.00, 10.0, 1.0, 0.003, 0.40]  
 - &default_leg_imp 	[1000.0, 20.0, 1.0, 0.005, 0.40] 
 - &default_leg_imp_lp 	[500.00, 10.0, 1.0, 0.003, 0.40]
 - &default_wheel	[050.00, 00.0, 0.0, 0.000, 00.0]
 - &upper_body_ctrl pos_3b
 - &lower_body_ctrl pos_3b 

#############################
# GENERIC ESC config
#############################

LpESC_X:
  control_mode: *upper_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 7.0
  pid :
    position: [100000.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp_lp

HpESC_X:
  sign: 1
  pos_offset: 0

CentAcESC_X:
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [220.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

HeriHandESC_X:
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 1.0]


#############################
# waist
#############################

CentAcESC_1:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: 1
  pos_offset: 0
  max_current_A: 20.0
  ram_cmd: [38]
  pid :
    position:   [1000.0 , 0.0 , 30.0]
    # pos_Kp pos_Kd tor_Kp tor_Kd tor_Ki
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp


##############################
# Right Arm

CentAcESC_11:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

CentAcESC_12:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

CentAcESC_13:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

CentAcESC_14:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  ram_cmd: [38]
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

CentAcESC_15:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp_lp

CentAcESC_16:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  ram_cmd: [38]
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp_lp

CentAcESC_17:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 0
  max_current_A: 6.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp_lp

##############################
# Left Arm

CentAcESC_21:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

CentAcESC_22:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 45
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

CentAcESC_23:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

CentAcESC_24:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  ram_cmd: [38]
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp

CentAcESC_25:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp_lp

CentAcESC_26:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  ram_cmd: [38]
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp_lp

CentAcESC_27:
  control_mode: *upper_body_ctrl
  fault_power_off: false
  sign: -1
  pos_offset: 0
  max_current_A: 6.0
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_arm_imp_lp

##############################
# FrontLeft Leg

CentAcESC_71:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 45
  max_current_A: 45.0
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_72:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 45.0
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_73:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 45.0
  ram_cmd: [38]
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_74:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  pid :
    position: [1000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_75:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [300.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp_lp

CentAcESC_76:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  ram_cmd: [38]
  pid :
    velocity: *default_wheel
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [20.0, 2.0, 0.0, 0.0, 0.0]


##############################
# FrontRight Leg

CentAcESC_41:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: -45
  max_current_A: 45.0
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_42:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 45.0
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_43:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 45.0
  ram_cmd: [38]
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_44:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 25.0
  pid :
    position: [1000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_45:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [300.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp_lp

CentAcESC_46:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  ram_cmd: [38]
  pid :
    velocity: *default_wheel
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [20.0, 0.0, 0.0, 0.0, 0.0]


##############################
# HindLeft Leg

CentAcESC_61:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: -45
  max_current_A: 45.0
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_62:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 45.0
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_63:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 45.0
  ram_cmd: [38]
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_64:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 25.0
  pid :
    position: [1000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_65:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [300.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp_lp

CentAcESC_66:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  ram_cmd: [38]
  pid :
    velocity: *default_wheel
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [20.0, 0.0, 0.0, 0.0, 0.0]


##############################
# HindRight Leg

CentAcESC_51:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 45
  max_current_A: 45.0
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_52:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 45.0
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_53:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 45.0
  ram_cmd: [38]
  pid :
    position: [2000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_54:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 25.0
  pid :
    position: [1000.0 , 0.0 , 50.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp

CentAcESC_55:
  control_mode: *lower_body_ctrl
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  pid :
    position: [300.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  *default_leg_imp_lp

CentAcESC_56:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  ram_cmd: [38]
  pid :
    velocity: *default_wheel
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [20.0, 0.0, 0.0, 0.0, 0.0]


LpESC_101:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 3.0
  pid:
    position: [100000.0, 0.0, 1.0]
    impedance: [0.0, 0.0, 0.0, 0.0, 0.0]

LpESC_102:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  max_current_A: 3.0
  pid:
    position: [100000.0, 0.0, 1.0]
    impedance: [0.0, 0.0, 0.0, 0.0, 0.0]

LpESC_103:
  control_mode: vel_71
  sign: 1
  pos_offset: 0
  max_current_A: 3.0
  pid:
    velocity: [6000.0, 0.0, 0.0]
    impedance: [0.0, 0.0, 0.0, 0.0, 0.0]

